/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface JdsButton {
        "customClass": string;
        "customStyle": { [key: string]: string };
        "disabled": boolean;
        "size": 'lg' | 'md' | 'sm' | 'icon-lg' | 'icon-md' | 'icon-sm';
        "solid": boolean;
        "variant": 'primary' | 'secondary' | 'tertiary' | 'warning' | 'danger' | 'link' | 'dropdown';
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLJdsButtonElement extends Components.JdsButton, HTMLStencilElement {
    }
    var HTMLJdsButtonElement: {
        prototype: HTMLJdsButtonElement;
        new (): HTMLJdsButtonElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "jds-button": HTMLJdsButtonElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface JdsButton {
        "customClass"?: string;
        "customStyle"?: { [key: string]: string };
        "disabled"?: boolean;
        "size"?: 'lg' | 'md' | 'sm' | 'icon-lg' | 'icon-md' | 'icon-sm';
        "solid"?: boolean;
        "variant"?: 'primary' | 'secondary' | 'tertiary' | 'warning' | 'danger' | 'link' | 'dropdown';
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "jds-button": JdsButton;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "jds-button": LocalJSX.JdsButton & JSXBase.HTMLAttributes<HTMLJdsButtonElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
